### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by petewilson-bsc** [riscv-software-src/riscv-perf-model#10]
Currently:
An extraction of the Map/Spara Example Performance Model based on the Sparta Modeling Framework, Olympia is a fully-features OoO CPU performance model for the RISC-V community.

Olympia is a trace-driven simulator runnig instructions streams defined in either JSON format or [STF](https://github.com/sparcians/stf_spec).

Better:

An extraction of the Map/Sparta Example Performance Model based on the Sparta Modeling Framework, Olympia is a fully-featured OoO RISC-V CPU performance model for the RISC-V community.

Olympia is a trace-driven simulator running instructions streams defined in either JSON format or [STF](https://github.com/sparcians/stf_spec).

**Comment by klingaard** [comment]
Fixed in commit https://github.com/riscv-software-src/riscv-perf-model/commit/24bb91609e6471363c45d5cf05445b957c297918
