### ISSUE TITLE
Typo in core/CPUTopology.hpp

### ISSUE THREAD

**Issue by zxc12523** [riscv-software-src/riscv-perf-model#106]
There is a typo in core/CPUTopology.hpp at line 102.

https://github.com/riscv-software-src/riscv-perf-model/blob/82504f6f68374d4b335d9de3d5d3890fe55e9838/core/CPUTopology.hpp#L102

It should be topology.

**Comment by klingaard** [comment]
Easy enough.  Thanks for pointing it out
