### ISSUE TITLE
Handling flush in LSU updateIssuePriorityAfterCacheReload

### ISSUE THREAD

**Issue by danbone** [riscv-software-src/riscv-perf-model#136]
@h0lyalg0rithm 

I'm trying to enable flushing and I'm hitting the assert in this code because the instruction was flushed.

https://github.com/riscv-software-src/riscv-perf-model/blob/e3e1412137f8b5ee647c223b31301538e4262039/core/LSU.cpp#L1178-L1196

Can I just return early if the instruction was flushed?

**Comment by ullahnasr** [comment]
The email knute.lingaard@sfive is no longer valid as Knute lingaard is not at Sifive anymore. He will update his emal address

**Comment by klingaard** [comment]
Thanks, Nasr.  I updated the settings.  You (in theory) shouldn't be receiving any more emails.

**Comment by danbone** [comment]
@h0lyalg0rithm see #137
