### ISSUE TITLE
Use HTTPS instead of SSH for submodules?

### ISSUE THREAD

**Issue by oms-vmicro** [riscv-software-src/riscv-perf-model#193]
There have been recent changes to the method `riscv-perf-model` clones its submodules.  Currently it is mixed with `stf_lib` and `fsl` using HTTPS and `mavis` using SSH ([link](https://github.com/riscv-software-src/riscv-perf-model/blob/master/.gitmodules)).

I'd like to propose `mavis` also switch back to using HTTPS so all submodules are cloned in a consistent way.  Though I'd like to understand if there's a reason to use SSH over HTTPS and/or do so for `mavis` but not `stf_lib` and `fsl`.

My basis for proposing HTTPS is that It is possible not all consumers of the `riscv-perf-model` will want to use SSH as I believe that requires them to have a GitHub account.  For read-only consumers, HTTPS is sufficient.  Non-GitHub users can still get around this by modifying their `.gitmodules` to use HTTPS instead of SSH but it's another step in getting started.

@jeffnye-gh @kathlenemagnus

**Comment by Shubhf** [comment]
hey @oms-vmicro Can I take up this issue?
I am thinking that switching mavis  to HTTPS would be a better option , as it would be a consistent and straightforward access for all users, particularly without git accounts, This not only helps to making it easier for new contributors, and indirectly will be helping new contributors to work with risk-perf-model

**Comment by klingaard** [comment]
There's no strong need.  Feel free to change it.

**Comment by Shubhf** [comment]
I have tried to make necessary changes @klingaard @oms-vmicro  Pls review and suggest what all I could do more[https://github.com/riscv-software-src/riscv-perf-model/pull/195
](#195 )
