### ISSUE TITLE
MAVIS submodule

### ISSUE THREAD

**Issue by orion160** [riscv-software-src/riscv-perf-model#196]
Missing `#include <cstdint>` at [DecoderTypes](https://github.com/sparcians/mavis/blob/055b22aedf891ab2e41b2e3ca0164e85d4f20484/mavis/DecoderTypes.h)

Which is fixed in a recent commit

**Comment by Shubhf** [comment]
@orion160 Can I take up this issue?

**Comment by orion160** [comment]
Hmmm feel free to submit a PR, though I am not a maintainer

**Comment by Shubhf** [comment]
Thanks, I will!

**Comment by Shubhf** [comment]
I have submitted a PR [https://github.com/sparcians/mavis/pull/18] ..Pls check and suggest me about the feedback
