### ISSUE TITLE
credits should be reduced with i in fetchinstructions()

### ISSUE THREAD

**Issue by dingiso** [riscv-software-src/riscv-perf-model#23]
The main loop in the function `fetchInstruction` will abnormally break when the ex_inst is nullptr. The number of insts which has been fetched will be less than the upper. I think the credits should be reduced with `i` not the upper.
Like this:
```cpp
uint32_t i = 0;
for(; i < upper; ++i)
    ...
credits_inst_queue_ -= i;
```

**Comment by knute-sifive** [comment]
Yep, good catch.
