### ISSUE TITLE
Improve statistics/counters in the LSU

### ISSUE THREAD

**Issue by knute-sifive** [riscv-software-src/riscv-perf-model#25]
We only have one counter -- `tlb_hits`.   Need more .. a lot more!

@arupc can you add a bunch?

**Comment by arupc-vmicro** [comment]
Some sample LSU stats:
dcache_hits/misses
tlb_hits/misses
occupany of fill buffers
hit on fills

**Comment by arupc-vmicro** [comment]
Added additional stats via https://github.com/riscv-software-src/riscv-perf-model/pull/30

Some proposed stats such as occupancy of fill buffers, hit on fills requires a cache model, which is not present at the moment. I will add these stats to the appropriate issue.
