### ISSUE TITLE
Add unit testing framework and unit tests for each component

### ISSUE THREAD

**Issue by klingaard** [riscv-software-src/riscv-perf-model#4]
Each component (Fetch, Decode, etc) should have its own unit test.  To facilitate this, a testing framework should be written first and each unit using that.

**Comment by knute-sifive** [comment]
First cut of a "common" set of source/sink units are made available in PR https://github.com/riscv-software-src/riscv-perf-model/pull/18

Next work to be done: generic simulator objects, although that might not be feasible.

**Comment by knute-sifive** [comment]
I'm going to consider this work complete for now.  I set up a common source and sink unit [here](https://github.com/riscv-software-src/riscv-perf-model/tree/master/test/core/common) and Aaron was able to make use of it in his Rename branch (with a few tweaks).
