### ISSUE TITLE
Enhance middle machine to enable dynamic topologies

### ISSUE THREAD

**Issue by klingaard** [riscv-software-src/riscv-perf-model#5]
Currently the olympia model has 1 ALU, 1 branch, etc and Dispatch is hard-coded to this topology.  Using Sparta's extension support, add a dynamic topology definition to allow a user to create different topologies.

This includes (as a start):

1. Defining the number of ALUs, branch units, load/store units, etc
2. Defining structures like instruction issuing queues and pipes (and the ratios for them)

**Comment by knute-sifive** [comment]
Work is complete.
