### ISSUE TITLE
All load_store instructions are marked as store Instructions

### ISSUE THREAD

**Issue by h0lyalg0rithm** [riscv-software-src/riscv-perf-model#78]
All the instructions which are load or store always return true when this function is called https://github.com/riscv-software-src/riscv-perf-model/blob/620b664797585beb6b42d3a1b004b708072d0f65/core/Inst.hpp#L173
The value for `isLoadStore()` is true if the instruction is either load or store.
https://github.com/riscv-software-src/riscv-perf-model/blob/620b664797585beb6b42d3a1b004b708072d0f65/core/InstArchInfo.hpp#L91

**Comment by AaronGChan** [comment]
Fixed in https://github.com/riscv-software-src/riscv-perf-model/pull/70.
